[book]
authors = ["ParkJuhyeong"]
language = "ko"
multilingual = false
src = "src"
title = "Borre κ°λ°λ…ΈνΈ"

[build]
build-dir = "docs"

[output.html]
cname = "borre-haechi-devnote.juhyung.dev"
theme = "src/theme"
default-theme = "light"